version: '3.8'

services:

 # api-gateway:
 #   build:
 #     context: .
 #     dockerfile: api-gateway.Dockerfile
 #   ports:
 #     - "8080:8080"
 #   depends_on:
 #     - consul

 # book-service:
 #   build:
 #     context: .
 #     dockerfile: book-service.Dockerfile
 #   ports:
 #     - "0:0"
 #   depends_on:
 #     - mongodb
 #     - rabbitmq



  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library-management


  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data
    command: "agent -dev -client 0.0.0.0"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user
      RABBITMQ_DEFAULT_PASS: rabbit_pass

volumes:
  mongodb_data:
  mysql_data:
  consul_data:
  rabbitmq_data:
