server:
    port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        health-check-path: /actuator/health
        query-passing: true

    gateway:
      routes:
        - id: book-service
          uri: lb://book-service/
          predicates:
            - Path=/api/books
        - id: library-catalog
          uri: lb://library-catalog/
          predicates:
            - Path=/api/library/**



    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: "http://localhost:3000"
          allowedHeaders:
            - "*"
          allowedMethods:
            - "GET"
            - "POST"
            - "OPTIONS"
  config:
    import: "optional:consul:"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
